### ISSUE TITLE
Converters need to be in the correct places.

### ISSUE THREAD

**Issue by robiRagan** [eduardoRubioG/MinimumRcpp#3]
Converters need to be in the correct places for both findParetoSet and kintersections:

Unless best practices for Rcpp packages have changed the converters should be implemented as forward declarations and then the actual converters.
-  forward declarations being in **inst/include/minimumRcpp.h** and 
- the converters being in **arc/minimumRcpp.cpp** as they are in the main code. As I understand it placing the converters in these places is best practices for Rcpp packages. If something has changed let me know.

**Comment by eduardoRubioG** [comment]
Completed -- in master now
