### ISSUE TITLE
kintersections returns the original polygons to the screen.

### ISSUE THREAD

**Issue by robiRagan** [eduardoRubioG/MinimumRcpp#5]
kintersections returns the original polygons to the screen when it runs. Make that an option of the function where the default is FALSE or remove that behavior from the function.

**Comment by eduardoRubioG** [comment]
Merged the fix into master. 

Added an optional parameter to the `kintersection` function that allows the user to print the input polygons if set to true. If omitted, the same function will execute but with the default value `false` and will not print the input polygons. If the parameter is set to `false` then it obviously won't print either.
