### ISSUE TITLE
The functions do not export correctly. 

### ISSUE THREAD

**Issue by robiRagan** [eduardoRubioG/MinimumRcpp#6]
The functions do not export correctly. When the package is loaded or rebuilt and reloaded the functions are not available to use. I believe that Roxygen is not updating NAMESPACE with export(findParetoSet) and export(kintersections). You may need #’ @export in the cpp code right before the [[Rcpp::export]].

**Comment by eduardoRubioG** [comment]
Merged branch `hotfix-exports` into `master` with resolutions to this issue. Master now has these fixes.
